// slime.js: a data pack, the format anyone can write (docs/PACKS.md). No code: sprites are character art,
// each state a loop of frames, props come from the shared effects. The same object, as JSON, can live in
// ~/.config/clawd/pets/<id>.json or be registered by another plugin with $.clawd.pack().
// One colour plus holes, like Clawd: in quad mode a cell holds two colours, so single-colour art stays crisp.

export default {
  format: 'cc-clawd/pack@1',
  id: 'slime',
  name: 'Slime',
  author: 'cc-clawd',
  description: 'A green slime that bounces when things go well and melts when they do not',
  cols: 17, rows: 3, mode: 'quad',
  palette: { '#': '#7bd88f' },
  at: [1, 1],
  anchor: [17, 0],
  look: [7, 2],
  sprites: {
    rest: [
      '....######....',
      '..##########..',
      '.###.####.###.',
      '##############',
      '##############',
    ],
    blink: [
      '....######....',
      '..##########..',
      '.############.',
      '##############',
      '##############',
    ],
    squish: [
      '..............',
      '...########...',
      '.####.##.####.',
      '##############',
      '##############',
    ],
    stretch: [
      '.....####.....',
      '...########...',
      '...#.####.#...',
      '..##########..',
      '...########...',
    ],
    up: [
      '....######....',
      '..##.####.##..',
      '.############.',
      '##############',
      '##############',
    ],
    low: [
      '..............',
      '..............',
      '...########...',
      '.####.##.####.',
      '##############',
    ],
    flat: [
      '..............',
      '..............',
      '...########...',
      '.############.',
      '##############',
    ],
    dizzyA: [
      '....######....',
      '..##########..',
      '.##.#####.###.',
      '##############',
      '##############',
    ],
    dizzyB: [
      '....######....',
      '..##########..',
      '.####.####.##.',
      '##############',
      '##############',
    ],
  },
  states: {
    idle: { frames: [['rest', 2200], ['blink', 130], ['rest', 1400], ['squish', 220], ['rest', 900]], fx: [['coffee', 18, 0]] },
    calm: { frames: [['rest', 2600], ['blink', 130]], fx: [['desk', 18, 0]] },
    happy: { frames: [['squish', 180], ['stretch', 200], ['up', 260]], fx: [['desk', 18, 0], ['notes', 15, 0]] },
    ecstatic: { frames: [['squish', 120], ['stretch', 160, 0, -1], ['up', 140]], fx: [['confetti', 18, 0, { n: 12 }]] },
    cheer: { frames: [['squish', 110], ['stretch', 150, 0, -1], ['up', 130]], fx: [['confetti', 18, 0, { n: 14 }], ['bang', 18, 0]] },
    worried: { frames: [['rest', 900], ['rest', 120, 1, 0], ['rest', 120, -1, 0]], fx: [['desk', 18, 0], ['sweat', 16, 0]] },
    sad: { frames: [['low', 1800], ['flat', 600]], fx: [['rain', 18, 0]] },
    sleep: { frames: [['flat', 2000], ['low', 2000]], fx: [['night', 18, 0]] },
    alert: { frames: [['stretch', 160], ['rest', 160]], fx: [['bell', 18, 0]] },
    needs: { frames: [['up', 700], ['rest', 700]], fx: [['ticket', 18, 0]] },
    think: { frames: [['rest', 240], ['squish', 120], ['rest', 240], ['blink', 110]], fx: [['laptop', 18, 0]] },
    dizzy: { frames: [['dizzyA', 140], ['dizzyB', 140]], fx: [['orbit', 18, 0]] },
  },
}
